# - Try to find LibEvent
# Once done this will define
#  LIBEVENT_FOUND - System has LibEvent
#  LIBEVENT_INCLUDE_DIRS - The LibEvent include directories
#  LIBEVENT_LIBRARIES - The libraries needed to use LibEvent

SET(LIBEVENT_FOUND NO)

FIND_PATH(LIBEVENT_INCLUDE_DIR event.h)
FIND_LIBRARY(LIBEVENT_LIBRARY NAMES event)

SET(LIBEVENT_LIBRARIES ${LIBEVENT_LIBRARY})
SET(LIBEVENT_INCLUDE_DIRS ${LIBEVENT_INCLUDE_DIR})

IF(LIBEVENT_LIBRARY)
	SET(LIBEVENT_FOUND YES)
ENDIF(LIBEVENT_LIBRARY)
